name: Deploy to Server

on:
  push:
    branches:
      - main  # chạy khi push vào nhánh main

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 206.189.92.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Project/HoleEatingLinux
            bash pull.sh

